### ISSUE TITLE
Document how third-party recipes can be transferred to the openrewrite org

### ISSUE THREAD

**Issue by rpau** [openrewrite/collaboration-proposals#2]
**Background**

Following the internal proposal to adopt recipes into OpenRewrite GitHub org, we should have a section in our documentation that describes how to transfer a third-party repository and create a ticket to add a team with write permissions in a specific repository.

**Acceptance Criteria**

- [ ] The docs are available and follow the proposal.

**Comment by JLLeitschuh** [comment]
Is the plan to have a process similar to Jenkins where all Jenkins plugins are under the Jenkins GitHub organization?

**Comment by mike-solomon** [comment]
I'm not sure what the plan for this is anymore. @timtebeek Is this still a thing? I know we had talked about this at one point but I don't know if we are still continuing with this or what the plan is.

**Comment by timtebeek** [comment]
I don't think we have to revisit this issue; at most we can add a link to this repository in the docs if we haven't already.
